# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Dev\Druid

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Dev\Druid

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Dev\Druid\CMakeFiles C:\Dev\Druid\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Dev\Druid\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named druid

# Build rule for target.
druid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 druid
.PHONY : druid

# fast build rule for target.
druid/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/build
.PHONY : druid/fast

src/application/application.obj: src/application/application.c.obj
.PHONY : src/application/application.obj

# target to build an object file
src/application/application.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/application/application.c.obj
.PHONY : src/application/application.c.obj

src/application/application.i: src/application/application.c.i
.PHONY : src/application/application.i

# target to preprocess a source file
src/application/application.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/application/application.c.i
.PHONY : src/application/application.c.i

src/application/application.s: src/application/application.c.s
.PHONY : src/application/application.s

# target to generate assembly for a file
src/application/application.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/application/application.c.s
.PHONY : src/application/application.c.s

src/core/arena.obj: src/core/arena.c.obj
.PHONY : src/core/arena.obj

# target to build an object file
src/core/arena.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/arena.c.obj
.PHONY : src/core/arena.c.obj

src/core/arena.i: src/core/arena.c.i
.PHONY : src/core/arena.i

# target to preprocess a source file
src/core/arena.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/arena.c.i
.PHONY : src/core/arena.c.i

src/core/arena.s: src/core/arena.c.s
.PHONY : src/core/arena.s

# target to generate assembly for a file
src/core/arena.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/arena.c.s
.PHONY : src/core/arena.c.s

src/core/hashmap.obj: src/core/hashmap.c.obj
.PHONY : src/core/hashmap.obj

# target to build an object file
src/core/hashmap.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/hashmap.c.obj
.PHONY : src/core/hashmap.c.obj

src/core/hashmap.i: src/core/hashmap.c.i
.PHONY : src/core/hashmap.i

# target to preprocess a source file
src/core/hashmap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/hashmap.c.i
.PHONY : src/core/hashmap.c.i

src/core/hashmap.s: src/core/hashmap.c.s
.PHONY : src/core/hashmap.s

# target to generate assembly for a file
src/core/hashmap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/hashmap.c.s
.PHONY : src/core/hashmap.c.s

src/core/input.obj: src/core/input.c.obj
.PHONY : src/core/input.obj

# target to build an object file
src/core/input.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/input.c.obj
.PHONY : src/core/input.c.obj

src/core/input.i: src/core/input.c.i
.PHONY : src/core/input.i

# target to preprocess a source file
src/core/input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/input.c.i
.PHONY : src/core/input.c.i

src/core/input.s: src/core/input.c.s
.PHONY : src/core/input.s

# target to generate assembly for a file
src/core/input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/input.c.s
.PHONY : src/core/input.c.s

src/core/math.obj: src/core/math.c.obj
.PHONY : src/core/math.obj

# target to build an object file
src/core/math.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/math.c.obj
.PHONY : src/core/math.c.obj

src/core/math.i: src/core/math.c.i
.PHONY : src/core/math.i

# target to preprocess a source file
src/core/math.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/math.c.i
.PHONY : src/core/math.c.i

src/core/math.s: src/core/math.c.s
.PHONY : src/core/math.s

# target to generate assembly for a file
src/core/math.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/math.c.s
.PHONY : src/core/math.c.s

src/core/obj_loader.obj: src/core/obj_loader.c.obj
.PHONY : src/core/obj_loader.obj

# target to build an object file
src/core/obj_loader.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/obj_loader.c.obj
.PHONY : src/core/obj_loader.c.obj

src/core/obj_loader.i: src/core/obj_loader.c.i
.PHONY : src/core/obj_loader.i

# target to preprocess a source file
src/core/obj_loader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/obj_loader.c.i
.PHONY : src/core/obj_loader.c.i

src/core/obj_loader.s: src/core/obj_loader.c.s
.PHONY : src/core/obj_loader.s

# target to generate assembly for a file
src/core/obj_loader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/obj_loader.c.s
.PHONY : src/core/obj_loader.c.s

src/core/transform.obj: src/core/transform.c.obj
.PHONY : src/core/transform.obj

# target to build an object file
src/core/transform.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/transform.c.obj
.PHONY : src/core/transform.c.obj

src/core/transform.i: src/core/transform.c.i
.PHONY : src/core/transform.i

# target to preprocess a source file
src/core/transform.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/transform.c.i
.PHONY : src/core/transform.c.i

src/core/transform.s: src/core/transform.c.s
.PHONY : src/core/transform.s

# target to generate assembly for a file
src/core/transform.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/core/transform.c.s
.PHONY : src/core/transform.c.s

src/stb_image.obj: src/stb_image.c.obj
.PHONY : src/stb_image.obj

# target to build an object file
src/stb_image.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/stb_image.c.obj
.PHONY : src/stb_image.c.obj

src/stb_image.i: src/stb_image.c.i
.PHONY : src/stb_image.i

# target to preprocess a source file
src/stb_image.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/stb_image.c.i
.PHONY : src/stb_image.c.i

src/stb_image.s: src/stb_image.c.s
.PHONY : src/stb_image.s

# target to generate assembly for a file
src/stb_image.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/stb_image.c.s
.PHONY : src/stb_image.c.s

src/systems/Physics/collider.obj: src/systems/Physics/collider.c.obj
.PHONY : src/systems/Physics/collider.obj

# target to build an object file
src/systems/Physics/collider.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Physics/collider.c.obj
.PHONY : src/systems/Physics/collider.c.obj

src/systems/Physics/collider.i: src/systems/Physics/collider.c.i
.PHONY : src/systems/Physics/collider.i

# target to preprocess a source file
src/systems/Physics/collider.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Physics/collider.c.i
.PHONY : src/systems/Physics/collider.c.i

src/systems/Physics/collider.s: src/systems/Physics/collider.c.s
.PHONY : src/systems/Physics/collider.s

# target to generate assembly for a file
src/systems/Physics/collider.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Physics/collider.c.s
.PHONY : src/systems/Physics/collider.c.s

src/systems/Rendering/camera.obj: src/systems/Rendering/camera.c.obj
.PHONY : src/systems/Rendering/camera.obj

# target to build an object file
src/systems/Rendering/camera.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/camera.c.obj
.PHONY : src/systems/Rendering/camera.c.obj

src/systems/Rendering/camera.i: src/systems/Rendering/camera.c.i
.PHONY : src/systems/Rendering/camera.i

# target to preprocess a source file
src/systems/Rendering/camera.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/camera.c.i
.PHONY : src/systems/Rendering/camera.c.i

src/systems/Rendering/camera.s: src/systems/Rendering/camera.c.s
.PHONY : src/systems/Rendering/camera.s

# target to generate assembly for a file
src/systems/Rendering/camera.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/camera.c.s
.PHONY : src/systems/Rendering/camera.c.s

src/systems/Rendering/display.obj: src/systems/Rendering/display.c.obj
.PHONY : src/systems/Rendering/display.obj

# target to build an object file
src/systems/Rendering/display.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/display.c.obj
.PHONY : src/systems/Rendering/display.c.obj

src/systems/Rendering/display.i: src/systems/Rendering/display.c.i
.PHONY : src/systems/Rendering/display.i

# target to preprocess a source file
src/systems/Rendering/display.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/display.c.i
.PHONY : src/systems/Rendering/display.c.i

src/systems/Rendering/display.s: src/systems/Rendering/display.c.s
.PHONY : src/systems/Rendering/display.s

# target to generate assembly for a file
src/systems/Rendering/display.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/display.c.s
.PHONY : src/systems/Rendering/display.c.s

src/systems/Rendering/mesh.obj: src/systems/Rendering/mesh.c.obj
.PHONY : src/systems/Rendering/mesh.obj

# target to build an object file
src/systems/Rendering/mesh.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/mesh.c.obj
.PHONY : src/systems/Rendering/mesh.c.obj

src/systems/Rendering/mesh.i: src/systems/Rendering/mesh.c.i
.PHONY : src/systems/Rendering/mesh.i

# target to preprocess a source file
src/systems/Rendering/mesh.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/mesh.c.i
.PHONY : src/systems/Rendering/mesh.c.i

src/systems/Rendering/mesh.s: src/systems/Rendering/mesh.c.s
.PHONY : src/systems/Rendering/mesh.s

# target to generate assembly for a file
src/systems/Rendering/mesh.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/mesh.c.s
.PHONY : src/systems/Rendering/mesh.c.s

src/systems/Rendering/shader.obj: src/systems/Rendering/shader.c.obj
.PHONY : src/systems/Rendering/shader.obj

# target to build an object file
src/systems/Rendering/shader.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/shader.c.obj
.PHONY : src/systems/Rendering/shader.c.obj

src/systems/Rendering/shader.i: src/systems/Rendering/shader.c.i
.PHONY : src/systems/Rendering/shader.i

# target to preprocess a source file
src/systems/Rendering/shader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/shader.c.i
.PHONY : src/systems/Rendering/shader.c.i

src/systems/Rendering/shader.s: src/systems/Rendering/shader.c.s
.PHONY : src/systems/Rendering/shader.s

# target to generate assembly for a file
src/systems/Rendering/shader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/shader.c.s
.PHONY : src/systems/Rendering/shader.c.s

src/systems/Rendering/texture.obj: src/systems/Rendering/texture.c.obj
.PHONY : src/systems/Rendering/texture.obj

# target to build an object file
src/systems/Rendering/texture.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/texture.c.obj
.PHONY : src/systems/Rendering/texture.c.obj

src/systems/Rendering/texture.i: src/systems/Rendering/texture.c.i
.PHONY : src/systems/Rendering/texture.i

# target to preprocess a source file
src/systems/Rendering/texture.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/texture.c.i
.PHONY : src/systems/Rendering/texture.c.i

src/systems/Rendering/texture.s: src/systems/Rendering/texture.c.s
.PHONY : src/systems/Rendering/texture.s

# target to generate assembly for a file
src/systems/Rendering/texture.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/Rendering/texture.c.s
.PHONY : src/systems/Rendering/texture.c.s

src/systems/WorldModel/ECS.obj: src/systems/WorldModel/ECS.c.obj
.PHONY : src/systems/WorldModel/ECS.obj

# target to build an object file
src/systems/WorldModel/ECS.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/WorldModel/ECS.c.obj
.PHONY : src/systems/WorldModel/ECS.c.obj

src/systems/WorldModel/ECS.i: src/systems/WorldModel/ECS.c.i
.PHONY : src/systems/WorldModel/ECS.i

# target to preprocess a source file
src/systems/WorldModel/ECS.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/WorldModel/ECS.c.i
.PHONY : src/systems/WorldModel/ECS.c.i

src/systems/WorldModel/ECS.s: src/systems/WorldModel/ECS.c.s
.PHONY : src/systems/WorldModel/ECS.s

# target to generate assembly for a file
src/systems/WorldModel/ECS.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\druid.dir\build.make CMakeFiles/druid.dir/src/systems/WorldModel/ECS.c.s
.PHONY : src/systems/WorldModel/ECS.c.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... druid
	@echo ... src/application/application.obj
	@echo ... src/application/application.i
	@echo ... src/application/application.s
	@echo ... src/core/arena.obj
	@echo ... src/core/arena.i
	@echo ... src/core/arena.s
	@echo ... src/core/hashmap.obj
	@echo ... src/core/hashmap.i
	@echo ... src/core/hashmap.s
	@echo ... src/core/input.obj
	@echo ... src/core/input.i
	@echo ... src/core/input.s
	@echo ... src/core/math.obj
	@echo ... src/core/math.i
	@echo ... src/core/math.s
	@echo ... src/core/obj_loader.obj
	@echo ... src/core/obj_loader.i
	@echo ... src/core/obj_loader.s
	@echo ... src/core/transform.obj
	@echo ... src/core/transform.i
	@echo ... src/core/transform.s
	@echo ... src/stb_image.obj
	@echo ... src/stb_image.i
	@echo ... src/stb_image.s
	@echo ... src/systems/Physics/collider.obj
	@echo ... src/systems/Physics/collider.i
	@echo ... src/systems/Physics/collider.s
	@echo ... src/systems/Rendering/camera.obj
	@echo ... src/systems/Rendering/camera.i
	@echo ... src/systems/Rendering/camera.s
	@echo ... src/systems/Rendering/display.obj
	@echo ... src/systems/Rendering/display.i
	@echo ... src/systems/Rendering/display.s
	@echo ... src/systems/Rendering/mesh.obj
	@echo ... src/systems/Rendering/mesh.i
	@echo ... src/systems/Rendering/mesh.s
	@echo ... src/systems/Rendering/shader.obj
	@echo ... src/systems/Rendering/shader.i
	@echo ... src/systems/Rendering/shader.s
	@echo ... src/systems/Rendering/texture.obj
	@echo ... src/systems/Rendering/texture.i
	@echo ... src/systems/Rendering/texture.s
	@echo ... src/systems/WorldModel/ECS.obj
	@echo ... src/systems/WorldModel/ECS.i
	@echo ... src/systems/WorldModel/ECS.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

