#include "../../../include/druid.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

b8 loadECSSystemDLL(const c8 *dllPath, ECSSystemDLL *out)
{
    if (!dllPath || !out) return false;
    memset(out, 0, sizeof(ECSSystemDLL));

    if (!dllLoad(dllPath, &out->dll))
    {
        ERROR("loadECSSystemDLL: failed to load %s", dllPath);
        return false;
    }

    // Try the new per-archetype naming convention first (druidGetECSSystem_<Name>)
    // Fall back to the legacy single-export name (druidGetECSSystem)
    GetECSSystemFn getSystem = NULL;
    if (out->name[0] != '\0')
    {
        c8 symbolName[256];
        snprintf(symbolName, sizeof(symbolName), "druidGetECSSystem_%s", out->name);
        getSystem = (GetECSSystemFn)dllSymbol(&out->dll, symbolName);
    }
    if (!getSystem)
        getSystem = (GetECSSystemFn)dllSymbol(&out->dll, "druidGetECSSystem");
    if (!getSystem)
    {
        ERROR("loadECSSystemDLL: missing druidGetECSSystem export in %s", dllPath);
        unloadECSSystemDLL(out);
        return false;
    }

    getSystem(&out->plugin);
    out->loaded = true;
    INFO("Loaded ECS system DLL: %s", dllPath);
    return true;
}

void unloadECSSystemDLL(ECSSystemDLL *dll)
{
    if (!dll) return;
    dllUnload(&dll->dll);
    dll->loaded = false;
}

b8 loadECSSystemFromHandle(DLLHandle *dll, const c8 *archetypeName, ECSSystemPlugin *out)
{
    if (!dll || !archetypeName || !out) return false;

    c8 symbolName[256];
    snprintf(symbolName, sizeof(symbolName), "druidGetECSSystem_%s", archetypeName);
    GetECSSystemFn getSystem = (GetECSSystemFn)dllSymbol(dll, symbolName);
    if (!getSystem)
    {
        // try legacy name
        getSystem = (GetECSSystemFn)dllSymbol(dll, "druidGetECSSystem");
    }
    if (!getSystem) return false;

    getSystem(out);
    return true;
}

//=====================================================================================================================
// Archetype code file generation
//=====================================================================================================================

b8 generateArchetypeFiles(const c8 *projectDir,
                           const c8 *archetypeName,
                           const FieldInfo *fields,
                           const c8 **typeNames,
                           u32 fieldCount,
                           b8 isSingle,
                           b8 isBuffered,
                           u32 poolCapacity,
                           b8 isPhysicsBody,
                           b8 useCpp)
{
    if (!projectDir || !archetypeName || !fields || !typeNames || fieldCount == 0)
    {
        ERROR("generateArchetypeFiles: invalid parameters");
        return false;
    }

    // Create camelCase version of name (e.g., "Bullet" → "bullet")
    c8 camelCaseName[256];
    if (archetypeName[0] != '\0')
    {
        snprintf(camelCaseName, sizeof(camelCaseName), "%c%s", tolower(archetypeName[0]), archetypeName + 1);
    }
    else
    {
        camelCaseName[0] = '\0';
    }

    // write header file
    c8 headerPath[MAX_PATH_LENGTH];
    snprintf(headerPath, sizeof(headerPath), "%s/src/%s.h", projectDir, archetypeName);

    FILE *hf = fopen(headerPath, "w");
    if (!hf)
    {
        ERROR("generateArchetypeFiles: cannot open %s", headerPath);
        return false;
    }

    fprintf(hf, "#pragma once\n");
    fprintf(hf, "// Auto-generated by the Druid editor — safe to edit below the stubs.\n");
    fprintf(hf, "#define DRUID_SYSTEM_EXPORT\n");
    if (useCpp) fprintf(hf, "#ifdef __cplusplus\nextern \"C\" {\n#endif\n");
    fprintf(hf, "#include <druid.h>\n");
    if (useCpp) fprintf(hf, "#ifdef __cplusplus\n}\n#endif\n");
    fprintf(hf, "\n");

    // archetype layout (extern — defined in .c, exported from DLL)
    fprintf(hf, "extern DSAPI FieldInfo  %s_fields[];\n", archetypeName);
    fprintf(hf, "extern DSAPI StructLayout %s_layout;\n\n", archetypeName);

    // system callbacks
    fprintf(hf, "DSAPI void %sInit(void);\n", camelCaseName);
    fprintf(hf, "DSAPI void %sUpdate(Archetype *arch, f32 dt);\n", camelCaseName);
    fprintf(hf, "DSAPI void %sRender(Archetype *arch, Renderer *r);\n", camelCaseName);
    fprintf(hf, "DSAPI void %sDestroy(void);\n\n", camelCaseName);

    // DLL entry point (unique per archetype so multiple systems can coexist in one DLL)
    fprintf(hf, "#ifdef __cplusplus\nextern \"C\" {\n#endif\n");
    fprintf(hf, "DSAPI void druidGetECSSystem_%s(ECSSystemPlugin *out);\n", archetypeName);
    fprintf(hf, "#ifdef __cplusplus\n}\n#endif\n");

    fclose(hf);

    // write source file
    c8 sourcePath[MAX_PATH_LENGTH];
    snprintf(sourcePath, sizeof(sourcePath), "%s/src/%s.%s", projectDir, archetypeName, useCpp ? "cpp" : "c");

    FILE *sf = fopen(sourcePath, "w");
    if (!sf)
    {
        ERROR("generateArchetypeFiles: cannot open %s", sourcePath);
        return false;
    }

    fprintf(sf, "#include \"%s.h\"\n\n", archetypeName);

    // Pool capacity define for buffered archetypes
    if (isBuffered)
    {
        fprintf(sf, "#define POOL_CAPACITY %u\n\n", poolCapacity);
    }

    // field layout (SOA)
    // Physics body archetypes auto-inject simulation fields appended after user fields.
    // PositionX/Y/Z are NOT injected here — they are part of the standard transform
    // prefix prepended by the editor (all archetypes use SoA positions).
    static const c8 *physFieldNames[] = {
        "LinearVelocityX", "LinearVelocityY", "LinearVelocityZ",
        "ForceX", "ForceY", "ForceZ",
        "PhysicsBodyType",
        "Mass", "InvMass", "Restitution", "LinearDamping",
        "SphereRadius",
        "ColliderHalfX", "ColliderHalfY", "ColliderHalfZ"
    };
    static const c8 *physFieldTypes[] = {
        "f32", "f32", "f32",
        "f32", "f32", "f32",
        "u32",
        "f32", "f32", "f32", "f32",
        "f32",
        "f32", "f32", "f32"
    };
    const u32 physFieldCount = isPhysicsBody ? 15u : 0u;
    const u32 totalFieldCount = fieldCount + physFieldCount;

    fprintf(sf, "// SOA field layout — matches the order used by getArchetypeFields()\n");
    fprintf(sf, "//\n");

    // If buffered, first field is always Alive
    if (isBuffered)
    {
        fprintf(sf, "//   [0] Alive  (b8)  - marks instances as active in the pool\n");
    }

    for (u32 i = 0; i < fieldCount; i++)
        fprintf(sf, "//   [%u] %s  (%s)\n", isBuffered ? i+1 : i, fields[i].name, typeNames[i]);
    for (u32 i = 0; i < physFieldCount; i++)
        fprintf(sf, "//   [%u] %s  (%s)  [physics — auto]\n", isBuffered ? fieldCount+i+1 : fieldCount+i, physFieldNames[i], physFieldTypes[i]);
    fprintf(sf, "//\n");
    fprintf(sf, "DSAPI FieldInfo %s_fields[] = {\n", archetypeName);

    // Add Alive field for buffered archetypes
    if (isBuffered)
    {
        fprintf(sf, "    { \"Alive\", sizeof(b8), FIELD_TEMP_COLD },\n");
    }

    for (u32 i = 0; i < totalFieldCount; i++)
    {
        const c8 *name = (i < fieldCount) ? fields[i].name    : physFieldNames[i - fieldCount];
        const c8 *type = (i < fieldCount) ? typeNames[i]      : physFieldTypes[i - fieldCount];
        FieldTemperature temp = (i < fieldCount) ? fields[i].temperature : FIELD_TEMP_HOT;
        const c8 *tempStr = (temp == FIELD_TEMP_HOT) ? "FIELD_TEMP_HOT" : "FIELD_TEMP_COLD";
        b8 last = (i + 1 == totalFieldCount);
        fprintf(sf, "    { \"%s\", sizeof(%s), %s }%s\n", name, type, tempStr, last ? "" : ",");
    }
    fprintf(sf, "};\n\n");

    fprintf(sf, "DSAPI StructLayout %s_layout = {\n", archetypeName);
    fprintf(sf, "    \"%s\",\n", archetypeName);
    fprintf(sf, "    %s_fields,\n", archetypeName);
    fprintf(sf, "    sizeof(%s_fields) / sizeof(FieldInfo)\n", archetypeName);
    fprintf(sf, "};\n\n");
    
    // Canonical archetype flags marker for robust scanner parsing.
    u8 generatedFlags = 0;
    if (isSingle && !isPhysicsBody) FLAG_SET(generatedFlags, ARCH_SINGLE);
    if (isBuffered)    FLAG_SET(generatedFlags, ARCH_BUFFERED);
    if (isPhysicsBody) FLAG_SET(generatedFlags, ARCH_PHYSICS_BODY);
    fprintf(sf, "// DRUID_FLAGS 0x%02X\n", generatedFlags);

    // Legacy marker comments for backward compatibility with older scanners.
    if (isBuffered)
    {
        fprintf(sf, "// isBuffered\n");
    }
    if (isSingle)
    {
        fprintf(sf, "// isSingle\n");
    }
    if (isPhysicsBody)
    {
        fprintf(sf, "// isPhysicsBody\n");
    }
    fprintf(sf, "\n");

    fprintf(sf, "static u32 s_ibSlot = (u32)-1;\n\n");

    fprintf(sf, "void %sInit(void)\n{\n", camelCaseName);
    fprintf(sf, "    s_ibSlot = rendererAcquireInstanceBuffer(renderer, 1024);\n");
    fprintf(sf, "}\n\n");

    fprintf(sf, "void %sUpdate(Archetype *arch, f32 dt)\n{\n", camelCaseName);
    if (isPhysicsBody)
        fprintf(sf, "    (void)dt; // physics step is driven by physWorldStep, not per-archetype dt\n");

    if (isSingle)
    {
        fprintf(sf, "    void **fields = getArchetypeFields(arch, 0);\n");
        fprintf(sf, "    if (!fields || arch->arena[0].count == 0) return;\n\n");
        u32 base = isBuffered ? 1u : 0u;
        if (isBuffered)
            fprintf(sf, "    b8 *alive = (b8 *)fields[0];\n");
        for (u32 i = 0; i < fieldCount; i++)
            fprintf(sf, "    %s *%s = (%s *)fields[%u];\n", typeNames[i], fields[i].name, typeNames[i], base + i);
        if (isPhysicsBody)
        {
            u32 pbase = base + fieldCount;
            fprintf(sf, "    // physics SoA fields (auto-injected)\n");
            for (u32 i = 0; i < physFieldCount; i++)
                fprintf(sf, "    %s *%s = (%s *)fields[%u];\n", physFieldTypes[i], physFieldNames[i], physFieldTypes[i], pbase + i);
        }
    }
    else
    {
        fprintf(sf, "    for (u32 _ch = 0; _ch < arch->activeChunkCount; _ch++)\n");
        fprintf(sf, "    {\n");
        fprintf(sf, "        void **fields = getArchetypeFields(arch, _ch);\n");
        fprintf(sf, "        if (!fields) continue;\n");
        fprintf(sf, "        u32 count = arch->arena[_ch].count;\n\n");
        u32 base = isBuffered ? 1u : 0u;
        if (isBuffered)
            fprintf(sf, "        b8 *alive = (b8 *)fields[0];\n");
        for (u32 i = 0; i < fieldCount; i++)
            fprintf(sf, "        %s *%s = (%s *)fields[%u];\n", typeNames[i], fields[i].name, typeNames[i], base + i);
        if (isPhysicsBody)
        {
            u32 pbase = base + fieldCount;
            fprintf(sf, "        // physics SoA fields (auto-injected)\n");
            for (u32 i = 0; i < physFieldCount; i++)
                fprintf(sf, "        %s *%s = (%s *)fields[%u];\n", physFieldTypes[i], physFieldNames[i], physFieldTypes[i], pbase + i);
        }
        fprintf(sf, "\n");
        if (isBuffered)
        {
            fprintf(sf, "        for (u32 i = 0; i < count; i++)\n");
            fprintf(sf, "        {\n");
            fprintf(sf, "            if (!alive[i]) continue;\n");
            fprintf(sf, "        }\n");
        }
        else
        {
            fprintf(sf, "        for (u32 i = 0; i < count; i++)\n");
            fprintf(sf, "        {\n");
            fprintf(sf, "        }\n");
        }
        fprintf(sf, "    }\n");
    }
    fprintf(sf, "}\n\n");

    fprintf(sf, "// Optional: implement custom rendering for this archetype.\n");
    fprintf(sf, "// When render is NULL (see druidGetECSSystem below), the engine uses a\n");
    fprintf(sf, "// default forward pass based on Position/Rotation/Scale/ModelID fields.\n");
    fprintf(sf, "// Uncomment and set out->render = %sRender to take full control.\n\n", camelCaseName);

    fprintf(sf, "/*\nvoid %sRender(Archetype *arch, Renderer *r)\n{\n", camelCaseName);
    fprintf(sf, "    (void)r;\n");
    fprintf(sf, "    for (u32 _ch = 0; _ch < arch->activeChunkCount; _ch++)\n");
    fprintf(sf, "    {\n");
    fprintf(sf, "        void **fields = getArchetypeFields(arch, _ch);\n");
    fprintf(sf, "        if (!fields) continue;\n");
    fprintf(sf, "        u32 count = arch->arena[_ch].count;\n\n");
    if (isBuffered)
    {
        fprintf(sf, "        b8 *alive = (b8 *)fields[0];\n");
        for (u32 i = 0; i < fieldCount; i++)
            fprintf(sf, "        %s *%s = (%s *)fields[%u];\n", typeNames[i], fields[i].name, typeNames[i], i + 1);
    }
    else
    {
        for (u32 i = 0; i < fieldCount; i++)
            fprintf(sf, "        %s *%s = (%s *)fields[%u];\n", typeNames[i], fields[i].name, typeNames[i], i);
    }
    fprintf(sf, "\n        for (u32 i = 0; i < count; i++)\n");
    fprintf(sf, "        {\n        }\n");
    fprintf(sf, "    }\n");
    fprintf(sf, "}\n*/\n\n");

    fprintf(sf, "void %sDestroy(void)\n{\n", camelCaseName);
    fprintf(sf, "    if (s_ibSlot != (u32)-1) { rendererReleaseInstanceBuffer(renderer, s_ibSlot); s_ibSlot = (u32)-1; }\n");
    fprintf(sf, "}\n\n");

    fprintf(sf, "void druidGetECSSystem_%s(ECSSystemPlugin *out)\n{\n", archetypeName);
    fprintf(sf, "    out->init    = %sInit;\n", camelCaseName);
    fprintf(sf, "    out->update  = %sUpdate;\n", camelCaseName);
    fprintf(sf, "    out->render  = NULL;  // default forward pass; set to %sRender for custom\n", camelCaseName);
    fprintf(sf, "    out->destroy = %sDestroy;\n", camelCaseName);
    fprintf(sf, "}\n");

    fclose(sf);

    INFO("Generated archetype files: %s.h / %s.%s in %s/src/", archetypeName, archetypeName, useCpp ? "cpp" : "c", projectDir);
    return true;
}

//=====================================================================================================================
// Build all archetype system DLLs
//=====================================================================================================================

b8 buildArchetypeSystems(const c8 *projectDir, c8 *outLog, u32 logSize)
{
    if (!projectDir || !outLog) return false;
    outLog[0] = '\0';

    // the main project CMakeLists already globs src/*.c — the archetype .c
    // files are compiled into the game DLL automatically. This function
    // triggers a rebuild so the latest system code is picked up.

    c8 buildDir[MAX_PATH_LENGTH];
    snprintf(buildDir, sizeof(buildDir), "%s/build", projectDir);
    createDir(buildDir);

    c8 cmd[2048];
    snprintf(cmd, sizeof(cmd),
             "cd /d \"%s/build\" && cmake --build . 2>&1", projectDir);

    FILE *pipe = (FILE *)platformPipeOpen(cmd);
    if (!pipe)
    {
        snprintf(outLog, logSize, "Failed to run cmake build for archetype systems\n");
        return false;
    }

    u32 off = 0;
    c8 line[512];
    while (fgets(line, sizeof(line), pipe))
    {
        u32 len = (u32)strlen(line);
        if (off + len < logSize - 1) { memcpy(outLog + off, line, len); off += len; }
    }
    outLog[off] = '\0';

    i32 ret = platformPipeClose(pipe);

    return (ret == 0);
}
