#include "../../../include/druid.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

//=====================================================================================================================
// ECS System DLL — load / unload (uses the unified DLL API from dllloader.c)
//=====================================================================================================================

b8 loadECSSystemDLL(const c8 *dllPath, ECSSystemDLL *out)
{
    if (!dllPath || !out) return false;
    memset(out, 0, sizeof(ECSSystemDLL));

    if (!dllLoad(dllPath, &out->dll))
    {
        ERROR("loadECSSystemDLL: failed to load %s", dllPath);
        return false;
    }

    // Try the new per-archetype naming convention first (druidGetECSSystem_<Name>)
    // Fall back to the legacy single-export name (druidGetECSSystem)
    GetECSSystemFn getSystem = NULL;
    if (out->name[0] != '\0')
    {
        c8 symbolName[256];
        snprintf(symbolName, sizeof(symbolName), "druidGetECSSystem_%s", out->name);
        getSystem = (GetECSSystemFn)dllSymbol(&out->dll, symbolName);
    }
    if (!getSystem)
        getSystem = (GetECSSystemFn)dllSymbol(&out->dll, "druidGetECSSystem");
    if (!getSystem)
    {
        ERROR("loadECSSystemDLL: missing druidGetECSSystem export in %s", dllPath);
        unloadECSSystemDLL(out);
        return false;
    }

    getSystem(&out->plugin);
    out->loaded = true;
    INFO("Loaded ECS system DLL: %s", dllPath);
    return true;
}

void unloadECSSystemDLL(ECSSystemDLL *dll)
{
    if (!dll) return;
    dllUnload(&dll->dll);
    dll->loaded = false;
}

b8 loadECSSystemFromHandle(DLLHandle *dll, const c8 *archetypeName, ECSSystemPlugin *out)
{
    if (!dll || !archetypeName || !out) return false;

    c8 symbolName[256];
    snprintf(symbolName, sizeof(symbolName), "druidGetECSSystem_%s", archetypeName);
    GetECSSystemFn getSystem = (GetECSSystemFn)dllSymbol(dll, symbolName);
    if (!getSystem)
    {
        // try legacy name
        getSystem = (GetECSSystemFn)dllSymbol(dll, "druidGetECSSystem");
    }
    if (!getSystem) return false;

    getSystem(out);
    return true;
}

//=====================================================================================================================
// Archetype code file generation
//
// For a given archetype name and field list, writes:
//   src/<name>.h   — archetype layout declaration + system function signatures
//   src/<name>.c   — field layout, system stubs (init/update/render/destroy), DLL export
//
// The generated code uses DSAPI (defined in druid.h) for export/import,
// so there are no per-archetype export macros.
//=====================================================================================================================

b8 generateArchetypeFiles(const c8 *projectDir,
                           const c8 *archetypeName,
                           const FieldInfo *fields,
                           const c8 **typeNames,
                           u32 fieldCount,
                           b8 isSingle,
                           b8 isBuffered,
                           u32 poolCapacity)
{
    if (!projectDir || !archetypeName || !fields || !typeNames || fieldCount == 0)
    {
        ERROR("generateArchetypeFiles: invalid parameters");
        return false;
    }

    // Create camelCase version of name (e.g., "Bullet" → "bullet")
    c8 camelCaseName[256];
    if (archetypeName[0] != '\0')
    {
        snprintf(camelCaseName, sizeof(camelCaseName), "%c%s", tolower(archetypeName[0]), archetypeName + 1);
    }
    else
    {
        camelCaseName[0] = '\0';
    }

    // ---- write header file ----
    c8 headerPath[MAX_PATH_LENGTH];
    snprintf(headerPath, sizeof(headerPath), "%s/src/%s.h", projectDir, archetypeName);

    FILE *hf = fopen(headerPath, "w");
    if (!hf)
    {
        ERROR("generateArchetypeFiles: cannot open %s", headerPath);
        return false;
    }

    fprintf(hf, "#pragma once\n");
    fprintf(hf, "// Auto-generated by the Druid editor — safe to edit below the stubs.\n");
    fprintf(hf, "#define DRUID_SYSTEM_EXPORT\n");
    fprintf(hf, "#include <druid.h>\n\n");

    // archetype layout (extern — defined in .c, exported from DLL)
    fprintf(hf, "extern DSAPI FieldInfo  %s_fields[];\n", archetypeName);
    fprintf(hf, "extern DSAPI StructLayout %s_layout;\n\n", archetypeName);

    // system callbacks
    fprintf(hf, "DSAPI void %sInit(void);\n", camelCaseName);
    fprintf(hf, "DSAPI void %sUpdate(Archetype *arch, f32 dt);\n", camelCaseName);
    fprintf(hf, "DSAPI void %sRender(Archetype *arch, Renderer *r);\n", camelCaseName);
    fprintf(hf, "DSAPI void %sDestroy(void);\n\n", camelCaseName);

    // DLL entry point (unique per archetype so multiple systems can coexist in one DLL)
    fprintf(hf, "#ifdef __cplusplus\nextern \"C\" {\n#endif\n");
    fprintf(hf, "DSAPI void druidGetECSSystem_%s(ECSSystemPlugin *out);\n", archetypeName);
    fprintf(hf, "#ifdef __cplusplus\n}\n#endif\n");

    fclose(hf);

    // ---- write source file ----
    c8 sourcePath[MAX_PATH_LENGTH];
    snprintf(sourcePath, sizeof(sourcePath), "%s/src/%s.c", projectDir, archetypeName);

    FILE *sf = fopen(sourcePath, "w");
    if (!sf)
    {
        ERROR("generateArchetypeFiles: cannot open %s", sourcePath);
        return false;
    }

    fprintf(sf, "#include \"%s.h\"\n\n", archetypeName);

    // Pool capacity define for buffered archetypes
    if (isBuffered)
    {
        fprintf(sf, "#define POOL_CAPACITY %u\n\n", poolCapacity);
    }

    // ---- field layout (SOA) ----
    fprintf(sf, "// SOA field layout — matches the order used by getArchetypeFields()\n");
    fprintf(sf, "//\n");
    
    // If buffered, first field is always Alive
    if (isBuffered)
    {
        fprintf(sf, "//   [0] Alive  (b8)  - marks instances as active in the pool\n");
    }
    
    for (u32 i = 0; i < fieldCount; i++)
        fprintf(sf, "//   [%u] %s  (%s)\n", isBuffered ? i+1 : i, fields[i].name, typeNames[i]);
    fprintf(sf, "//\n");
    fprintf(sf, "DSAPI FieldInfo %s_fields[] = {\n", archetypeName);
    
    // Add Alive field for buffered archetypes
    if (isBuffered)
    {
        fprintf(sf, "    { \"Alive\", sizeof(b8) },\n");
    }
    
    for (u32 i = 0; i < fieldCount; i++)
    {
        fprintf(sf, "    { \"%s\", sizeof(%s) }%s\n",
                fields[i].name, typeNames[i],
                (i + 1 < fieldCount) ? "," : "");
    }
    fprintf(sf, "};\n\n");

    fprintf(sf, "DSAPI StructLayout %s_layout = {\n", archetypeName);
    fprintf(sf, "    \"%s\",\n", archetypeName);
    fprintf(sf, "    %s_fields,\n", archetypeName);
    fprintf(sf, "    sizeof(%s_fields) / sizeof(FieldInfo)\n", archetypeName);
    fprintf(sf, "};\n\n");
    
    // Add marker comment for scanning
    if (isBuffered)
    {
        fprintf(sf, "// isBuffered\n");
    }
    if (isSingle)
    {
        fprintf(sf, "// isSingle\n");
    }
    fprintf(sf, "\n");

    fprintf(sf, "static u32 s_ibSlot = (u32)-1;\n\n");

    fprintf(sf, "void %sInit(void)\n{\n", camelCaseName);
    fprintf(sf, "    s_ibSlot = rendererAcquireInstanceBuffer(renderer, 1024);\n");
    fprintf(sf, "}\n\n");

    fprintf(sf, "void %sUpdate(Archetype *arch, f32 dt)\n{\n", camelCaseName);
    fprintf(sf, "    void **fields = getArchetypeFields(arch, 0);\n");
    fprintf(sf, "    u32    count  = arch->arena[0].count;\n\n");

    // typed field casts
    if (isBuffered)
    {
        fprintf(sf, "    b8 *alive = (b8 *)fields[0];\n");
        for (u32 i = 0; i < fieldCount; i++)
            fprintf(sf, "    %s *%s = (%s *)fields[%u];\n", typeNames[i], fields[i].name, typeNames[i], i + 1);
    }
    else
    {
        for (u32 i = 0; i < fieldCount; i++)
            fprintf(sf, "    %s *%s = (%s *)fields[%u];\n", typeNames[i], fields[i].name, typeNames[i], i);
    }
    fprintf(sf, "\n");

    if (isSingle)
    {
        fprintf(sf, "    if (count == 0) return;\n");
    }
    else if (isBuffered)
    {
        fprintf(sf, "    for (u32 i = 0; i < count; i++)\n");
        fprintf(sf, "    {\n");
        fprintf(sf, "        if (!alive[i]) continue;\n");
        fprintf(sf, "    }\n");
    }
    else
    {
        fprintf(sf, "    for (u32 i = 0; i < count; i++)\n");
        fprintf(sf, "    {\n");
        fprintf(sf, "    }\n");
    }
    fprintf(sf, "}\n\n");

    fprintf(sf, "// Optional: implement custom rendering for this archetype.\n");
    fprintf(sf, "// When render is NULL (see druidGetECSSystem below), the engine uses a\n");
    fprintf(sf, "// default forward pass based on Position/Rotation/Scale/ModelID fields.\n");
    fprintf(sf, "// Uncomment and set out->render = %sRender to take full control.\n\n", camelCaseName);

    fprintf(sf, "/*\nvoid %sRender(Archetype *arch, Renderer *r)\n{\n", camelCaseName);
    fprintf(sf, "    void **fields = getArchetypeFields(arch, 0);\n");
    fprintf(sf, "    u32    count  = arch->arena[0].count;\n\n");

    // typed field casts (same as update)
    // If buffered, first field is Alive
    if (isBuffered)
    {
        fprintf(sf, "    b8 *alive = (b8 *)fields[0];\n");
        for (u32 i = 0; i < fieldCount; i++)
            fprintf(sf, "    %s *%s = (%s *)fields[%u];\n", typeNames[i], fields[i].name, typeNames[i], i + 1);
    }
    else
    {
        for (u32 i = 0; i < fieldCount; i++)
            fprintf(sf, "    %s *%s = (%s *)fields[%u];\n", typeNames[i], fields[i].name, typeNames[i], i);
    }
    fprintf(sf, "\n    (void)r;\n    (void)arch;\n    (void)count;\n");
    fprintf(sf, "}\n*/\n\n");

    fprintf(sf, "void %sDestroy(void)\n{\n", camelCaseName);
    fprintf(sf, "    if (s_ibSlot != (u32)-1) { rendererReleaseInstanceBuffer(renderer, s_ibSlot); s_ibSlot = (u32)-1; }\n");
    fprintf(sf, "}\n\n");

    fprintf(sf, "void druidGetECSSystem_%s(ECSSystemPlugin *out)\n{\n", archetypeName);
    fprintf(sf, "    out->init    = %sInit;\n", camelCaseName);
    fprintf(sf, "    out->update  = %sUpdate;\n", camelCaseName);
    fprintf(sf, "    out->render  = NULL;  // default forward pass; set to %sRender for custom\n", camelCaseName);
    fprintf(sf, "    out->destroy = %sDestroy;\n", camelCaseName);
    fprintf(sf, "}\n");

    fclose(sf);

    INFO("Generated archetype files: %s.h / %s.c in %s/src/", archetypeName, archetypeName, projectDir);
    return true;
}

//=====================================================================================================================
// Build all archetype system DLLs
//=====================================================================================================================

b8 buildArchetypeSystems(const c8 *projectDir, c8 *outLog, u32 logSize)
{
    if (!projectDir || !outLog) return false;
    outLog[0] = '\0';

    // the main project CMakeLists already globs src/*.c — the archetype .c
    // files are compiled into the game DLL automatically. This function
    // triggers a rebuild so the latest system code is picked up.

    c8 buildDir[MAX_PATH_LENGTH];
    snprintf(buildDir, sizeof(buildDir), "%s/build", projectDir);
    createDir(buildDir);

    c8 cmd[2048];
    snprintf(cmd, sizeof(cmd),
             "cd /d \"%s/build\" && cmake --build . 2>&1", projectDir);

    FILE *pipe = (FILE *)platformPipeOpen(cmd);
    if (!pipe)
    {
        snprintf(outLog, logSize, "Failed to run cmake build for archetype systems\n");
        return false;
    }

    u32 off = 0;
    c8 line[512];
    while (fgets(line, sizeof(line), pipe))
    {
        u32 len = (u32)strlen(line);
        if (off + len < logSize - 1) { memcpy(outLog + off, line, len); off += len; }
    }
    outLog[off] = '\0';

    i32 ret = platformPipeClose(pipe);

    return (ret == 0);
}
